name: CI

on:
  push:
    branches: [ master ]

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD }}
          repository: treeloc/frontend
          dockerfile: Dockerfile
          tags: latest
          tag_with_sha: true
